### ISSUE TITLE
KeyError: 'quals'

### ISSUE THREAD

**Issue by lynnna-xu** [migalkin/NodePiece#2] opened 2021-11-30 08:27 UTC
Hi,

Thanks for the great work. I was trying to run node prediction experiment on my local machine. Was prompted key error of 'quals'. Later in the code I found that subtype="triples" if config["STATEMENT_LEN"] == 3 else "statements". When subtype=triples, quals is None. However, in the demo run command, STATEMENT_LEN is 3 hence such error occurs. Please correct me if I am wrong. Would be good if you could update a workable set-up. Thank you.

**Comment by migalkin** [comment] 2021-12-02 21:49
Hi, 

I can't reproduce the error from your description - could you please post the error stack trace? I'm running the command in the clean env with packages from `requirements.txt` with CLI args exactly as specified in the readme and there are no KeyErrors.

**Comment by lynnna-xu** [comment] 2021-12-03 05:33
> Hi,
> 
> I can't reproduce the error from your description - could you please post the error stack trace? I'm running the command in the clean env with packages from `requirements.txt` with CLI args exactly as specified in the readme and there are no KeyErrors.

Hi,

The issue seems not relevant to the environment or packages. Below is the traceback record for your reference. The command I used was as follows. 

python run_nc.py DATASET wd50k MAX_QPAIRS 3 STATEMENT_LEN 3 LABEL_SMOOTHING 0.1 EVAL_EVERY 5 DEVICE cpu WANDB True EPOCHS 40 GCN_HID_DROP2 0.5 GCN_HID_DROP 0.5 GCN_FEAT_DROP 0.5 EMBEDDING_DIM 100 GCN_GCN_DIM 100 LEARNING_RATE 0.001 GCN_ATTENTION True GCN_GCN_DROP 0.3 GCN_ATTENTION_DROP 0.3 GCN_LAYERS 3 DS_TYPE transductive MODEL_NAME stare TR_RATIO 0.05 USE_FEATURES False TOKENIZE True NUM_ANCHORS 50 MAX_PATHS 10 USE_TEST True

Traceback (most recent call last):
  File "run_nc.py", line 307, in <module>
    trace = training_loop(**args)
  File "/Users/lynn/PycharmProjects/7643-GNN/NodePiece/nc/loops/loops.py", line 51, in training_loop_pyg_nc
    pred = model(train_graph.to(device=device), train_mask_)
  File "/Users/lynn/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/lynn/PycharmProjects/7643-GNN/NodePiece/nc/models_nc.py", line 41, in forward
    all_ent, rels = self.forward_base(graph, self.hidden_drop, self.feature_drop)
  File "/Users/lynn/PycharmProjects/7643-GNN/NodePiece/nc/models/gnn_encoder.py", line 129, in forward_base
    x, edge_index, edge_type, quals = graph['x'], graph['edge_index'], graph['edge_type'], graph['quals']
  File "/Users/lynn/opt/anaconda3/lib/python3.8/site-packages/torch_geometric/data/data.py", line 354, in __getitem__
    return self._store[key]
  File "/Users/lynn/opt/anaconda3/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 68, in __getitem__
    return self._mapping[key]
KeyError: 'quals'

**Comment by migalkin** [comment] 2021-12-03 17:18
The command you posted works for me without problems, this is strange 🤔 
Which version of torch-geometric are you using?

**Comment by lynnna-xu** [comment] 2021-12-04 05:48
Hi, I'm using 2.0.1 since I can only use torch 1.8.0 in my environment. I feel the error arises due to the to_sparse_graph function. Based on the logic in the code, subtype="triples" if config["STATEMENT_LEN"] == 3. When subtype is "triples", quals is None according to the following definition. Please correct me if I'm wrong. 

def to_sparse_graph(edges, subtype, entoid, prtoid, maxlen):

    edge_index, edge_type = np.zeros((2, len(edges)), dtype='int64'), np.zeros((len(edges)), dtype='int64')
    qualifier_rel = []
    qualifier_ent = []
    qualifier_edge = []
    quals = None

    for i, st in enumerate(edges):
        edge_index[:, i] = [entoid[st[0]], entoid[st[2]]]
        edge_type[i] = prtoid[st[1]]

        if subtype == 'statements':
            qual_rel = np.array([prtoid[r] for r in st[3::2]])[
                       :(maxlen - 3) // 2]  # cut to the max allowed qualifiers per statement
            qual_ent = np.array([entoid[e] for e in st[4::2]])[
                       :(maxlen - 3) // 2]  # cut to the max allowed qualifiers per statement
            for j in range(qual_ent.shape[0]):
                qualifier_rel.append(qual_rel[j])
                qualifier_ent.append(qual_ent[j])
                qualifier_edge.append(i)

    if subtype == 'statements':
        quals = np.stack((qualifier_rel, qualifier_ent, qualifier_edge), axis=0)

    return edge_index, edge_type, quals

**Comment by migalkin** [comment] 2021-12-04 16:41
`quals` are always assigned to None for the existing node classification dataset, then this value is attached to the PyG Data object in the data loader:

https://github.com/migalkin/NodePiece/blob/d731c9990cdd7835f01f129f6134c3bff576821f/nc/data_loaders/clean_datasets.py#L130-L133

Then we can safely assume `quals` becomes part of the `train_graph` PyG object with value `None`. 
If you didn't change any code in the dataloader, I'm puzzled why this doesn't work - maybe there were some breaking changes in PyG 2.0 in addressing the Data object - I'll need to test it further.  

Anyways, for now, you can fix that by removing `quals` from this line, it shouldn't break anything

https://github.com/migalkin/NodePiece/blob/d731c9990cdd7835f01f129f6134c3bff576821f/nc/models/gnn_encoder.py#L129 

to this:
```
x, edge_index, edge_type = graph['x'], graph['edge_index'], graph['edge_type']
```

**Comment by lynnna-xu** [comment] 2021-12-05 05:51
Thanks Migalkin. I changed that line and there are some further changes required to avoid variable reference before assignment. Hence, instead, I commented the "if subtype == 'statements'" clause in to_sparse_graph function. This outputs quals as an empty numpy array which I assume wouldn't influence any downstream processing. Please let me know if this is inappropriate. 

def to_sparse_graph(edges, subtype, entoid, prtoid, maxlen):
    edge_index, edge_type = np.zeros((2, len(edges)), dtype='int64'), np.zeros((len(edges)), dtype='int64')
    qualifier_rel = []
    qualifier_ent = []
    qualifier_edge = []
    quals = None

    for i, st in enumerate(edges):
        edge_index[:, i] = [entoid[st[0]], entoid[st[2]]]
        edge_type[i] = prtoid[st[1]]

        #if subtype == 'statements':
        qual_rel = np.array([prtoid[r] for r in st[3::2]])[
                   :(maxlen - 3) // 2]  # cut to the max allowed qualifiers per statement
        qual_ent = np.array([entoid[e] for e in st[4::2]])[
                   :(maxlen - 3) // 2]  # cut to the max allowed qualifiers per statement
        for j in range(qual_ent.shape[0]):
            qualifier_rel.append(qual_rel[j])
            qualifier_ent.append(qual_ent[j])
            qualifier_edge.append(i)

    #if subtype == 'statements':
    quals = np.stack((qualifier_rel, qualifier_ent, qualifier_edge), axis=0)
    return edge_index, edge_type, quals

**Comment by migalkin** [comment] 2021-12-06 05:59
If there are further issues with variable referencing after that comment, then ideally I'd rather see what's going on there on a bigger picture and why you still keep getting those errors. 

If your new fix makes the forward/backward passes work - that's good, `quals` should not be used in the gnn layers anyways so I wouldn't expect any influence on downstream processing. 

Could you please elaborate on your setup so I could reproduce smth - you're running this code clean w/o any changes on torch1.8 + pyg 2.0.1, right?

**Comment by lynnna-xu** [comment] 2021-12-07 05:43
Thank you so much for putting in the effort to maintain this project. Below you may find a list of package versions in my environment. Hope it helps.

numpy==1.20.1
pykeen==1.0.5
python_igraph==0.9.8
scikit_learn==1.0.1
torch==1.8.0
torch_geometric==2.0.1
torch_scatter==2.0.8
tqdm==4.59.0

**Closed as completed** 2021-12-25 20:39 UTC

**Comment by migalkin** [comment] 2021-12-25 20:42
@lynnna-xu I reproduced the error in this environment - it appears due to a new procedure of creating a pyg Data object. In PyG > 2.0 `GlobalStorage` uses `setattr(object, key, value)` which does not work for keys with `None` values. That's why internally
```python
setattr(data, quals, None)
```
does not create the `quals` attribute. 

I fixed that to manual initialization of quals to some value (0 in this case), and it doesn't affect the training process anyhow, so the training works ok now. Please let me know if that fixed an issue at your side.

For reference: a similar issue in the PyG repo: https://github.com/pyg-team/pytorch_geometric/issues/3513
